### ISSUE TITLE
Make default TV selection more unbiased

### ISSUE THREAD

**Issue by bartlomiejb** [zaps166/QMPlay2OnlineContents#1]
The only TV station in default streams list is TV Republika. It is a heavily biased pro-government right-wing propaganda outlet, not a reliable source of information. See eg. the book "Media Accountability in the Era of Post-Truth Politics: European Challenges and Perspectives" by Tobias Eberwein, Susanne Fengler, Matthias Karmasin. I attached an excerpt that I found in [Google Books](https://books.google.pl/books?id=L5qfDwAAQBAJ&pg=PT96&lpg=PT96&dq=tv+republika+opinions&source=bl&ots=1PKPWj3_Cz&sig=ACfU3U2m2-ECwCotDvH7rBmln_cPp2Kq-g&hl=pl&sa=X&ved=2ahUKEwjps6iKmq_pAhWlw6YKHUc3Cd04ChDoATAHegQIBRAB#v=onepage&q=tv%20republika%20opinions&f=false).
![google-books-tv-republika](https://user-images.githubusercontent.com/4763259/81745841-d0b10c00-94a5-11ea-86a7-5872e283e371.png)

My proposal is to either remove this TV station from the default list or make the list more unbiased by adding links to other TV stations, more unbiased, or left-/central-leaning.

The list of streams (URL) is hardcoded in source code of QMPlay2 now.

**Comment by zaps166** [comment]
I wonder if somebody which gave me this is still using this link, but I don't care.
If you want to add something, create a PR - I'll check it.

**Comment by bartlomiejb** [comment]
Non-issue after [this change](https://github.com/zaps166/QMPlay2OnlineContents/commit/af3894f8d2e9418cc2f2990ea20b44b3283c13e2). Thanks!
