### ISSUE TITLE
Error when searching at MyFreeMp3

### ISSUE THREAD

**Issue by unspacyar** [zaps166/QMPlay2OnlineContents#2]
Hello.  Any search that I tried to do using MyFreeMp3 option at MediaBrowser, get this error message:

Failed to resolve hostname new.myfreemp3juices.ccapi: No address associated with hostname

Apparently the slash (/) is missing between CC and API (I guess the correct URL is new.myfreemp3juices.cc/api)

I am using QMPlay2 version 22.08.21 (i386) running on Haiku.

**Comment by zaps166** [comment]
Again... They're changing something there often.

**Comment by zaps166** [comment]
Fixed!

**Comment by unspacyar** [comment]
Awesome!!  It is working now.  Thank you so much!
And thank you for the entire QMplay2 team for this great application! ;-)
